import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PetShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black/[0.85] antialised bg-grid-white/[0.02]">
      <Navbar/>
        <main >
          {children}
          <Footer/>
        </main>
      </body>
    </html>
  );
}
